### ISSUE TITLE
Panic when the viewport width is too small to avoid wrapping

### ISSUE THREAD

**Issue by stepchowfun** [dfhoughton/colonnade#2]
Hello! I have this snippet:

```rs
let mut colonnade = Colonnade::new(2, terminal_width).unwrap();
for line in colonnade.tabulate(data).unwrap() {
    println!("{line}");
}
```

It works in general but panics when `terminal_width` is 1 column smaller than would be needed to avoid wrapping. Here is an example stack trace:

```
thread 'main' panicked at 'attempt to subtract with overflow', /Users/stephanboyer/.cargo/registry/src/github.com-1ecc6299db9ec823/colonnade-1.3.2/src/lib.rs:1388:34
stack backtrace:
   0:        0x1049f7fa2 - std::backtrace_rs::backtrace::libunwind::trace::h3274e49b4ebf7e53
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:        0x1049f7fa2 - std::backtrace_rs::backtrace::trace_unsynchronized::hd211d632c7624604
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:        0x1049f7fa2 - std::sys_common::backtrace::_print_fmt::h1e774fa26a8ee490
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:66:5
   3:        0x1049f7fa2 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd2e8cbde22b780fc
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:45:22
   4:        0x104a0ecfa - core::fmt::write::hd6692086cdd356a7
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/fmt/mod.rs:1202:17
   5:        0x1049f545c - std::io::Write::write_fmt::h6043124a2486acbb
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/io/mod.rs:1679:15
   6:        0x1049f969b - std::sys_common::backtrace::_print::h3d78a31fac988d9b
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:48:5
   7:        0x1049f969b - std::sys_common::backtrace::print::hdfd67a42b253a0c5
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:35:9
   8:        0x1049f969b - std::panicking::default_hook::{{closure}}::h87a12b8b06887dd7
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:295:22
   9:        0x1049f93a7 - std::panicking::default_hook::h7f68dad17e0bfaa4
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:314:9
  10:        0x1049f9cbf - std::panicking::rust_panic_with_hook::hd57427cbbfc3717a
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:698:17
  11:        0x1049f9bc2 - std::panicking::begin_panic_handler::{{closure}}::h33aab6d04e2bba70
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:586:13
  12:        0x1049f8438 - std::sys_common::backtrace::__rust_end_short_backtrace::h0e7a76f927db9964
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:138:18
  13:        0x1049f98cd - rust_begin_unwind
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:584:5
  14:        0x104a1e933 - core::panicking::panic_fmt::hcf6f3c517c6f3cb3
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:142:14
  15:        0x104a1e817 - core::panicking::panic::h46977cf6deabee02
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:48:5
  16:        0x104635fad - colonnade::Colonnade::lay_out::hf9e8f346004a34de
                               at /Users/stephanboyer/.cargo/registry/src/github.com-1ecc6299db9ec823/colonnade-1.3.2/src/lib.rs:1388:34
  17:        0x104636e5c - colonnade::Colonnade::macerate::h98061dc267349f11
                               at /Users/stephanboyer/.cargo/registry/src/github.com-1ecc6299db9ec823/colonnade-1.3.2/src/lib.rs:963:9
  18:        0x1046371b8 - colonnade::Colonnade::tabulate::hca79eb78cde75425
                               at /Users/stephanboyer/.cargo/registry/src/github.com-1ecc6299db9ec823/colonnade-1.3.2/src/lib.rs:878:9
  19:        0x1046419f8 - tagref::print_tabulated::h8fe4a458aeabb0c9
                               at /Users/stephanboyer/Desktop/Dropbox/projects/tagref/src/main.rs:126:17
  20:        0x104642412 - tagref::entry::h8672f870056e09e9
                               at /Users/stephanboyer/Desktop/Dropbox/projects/tagref/src/main.rs:180:13
  21:        0x1046438f7 - tagref::main::h8f10bd4b2e2c3a5b
                               at /Users/stephanboyer/Desktop/Dropbox/projects/tagref/src/main.rs:344:21
  22:        0x104621e7e - core::ops::function::FnOnce::call_once::hc2e796dc9682aae9
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/ops/function.rs:248:5
  23:        0x10462d4e1 - std::sys_common::backtrace::__rust_begin_short_backtrace::hd5bd8fc62a16dc93
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:122:18
  24:        0x1046205c4 - std::rt::lang_start::{{closure}}::h3bc0a0546b56cf5d
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/rt.rs:166:18
  25:        0x1049f17ee - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hb30f3c124d6422bd
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/ops/function.rs:283:13
  26:        0x1049f17ee - std::panicking::try::do_call::h6ab65f1fbf11caa5
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:492:40
  27:        0x1049f17ee - std::panicking::try::hb963b3a8541f11db
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:456:19
  28:        0x1049f17ee - std::panic::catch_unwind::hd044952603e5f56c
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panic.rs:137:14
  29:        0x1049f17ee - std::rt::lang_start_internal::{{closure}}::h3a2dc7ba533401e5
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/rt.rs:148:48
  30:        0x1049f17ee - std::panicking::try::do_call::h88480942a6edc3bf
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:492:40
  31:        0x1049f17ee - std::panicking::try::ha84f131c957dae86
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:456:19
  32:        0x1049f17ee - std::panic::catch_unwind::hab613c35aec6b94f
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panic.rs:137:14
  33:        0x1049f17ee - std::rt::lang_start_internal::ha5deaf08dab8765b
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/rt.rs:148:20
  34:        0x104620597 - std::rt::lang_start::hf3097469f68f3768
                               at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/rt.rs:165:17
  35:        0x104643a5b - _main
  36:     0x7ff8061d341f - <unknown>
```

So it looks like this subtraction is panicking:

https://github.com/dfhoughton/colonnade/blob/c6a1ec37aad3d50313bb2ebd9d4d2a30dedad146/src/lib.rs#L1388

I'm using Colonnade version 1.3.2.

**Comment by dfhoughton** [comment]
Thanks for reporting this, @stepchowfun . I can't say I'll address this immediately but I'll try to do so soon.
